### ISSUE TITLE
User Permissions

### ISSUE THREAD

**Issue by okrplay** [azuma-chat/azuma_backend#2]
Permissions should be saved as a bitfield with the following options, for now:
- Admin (Every permissions, right now this is only Manage Channels)
- Manage Channels (Create, modify and delete)

**Comment by Stupremee** [comment]
Wouldn’t it be better if we split the manage channel permission into separate permissions for creating modifying and deleting? We can have up to 64 (or even 128) different permissions so there is no need to save up permissions

**Comment by okrplay** [comment]
I think it would be more annoying to people when they always have to switch all three permissions - I couldn't think of a case where you would need to seperate those.
